# Generated by Django 4.2.2 on 2023-07-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_categoria_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', ', puede visualizar Catálogo de Vehículos')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
